import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :the_maestro, TheMaestroWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure Finch pools for HTTP clients - Production (optimized for performance)
config :the_maestro, :finch_pools,
  anthropic: [
    pool_config: [size: 15, count: 3],
    base_url: "https://api.anthropic.com"
  ],
  openai: [
    pool_config: [size: 15, count: 3],
    base_url: "https://api.openai.com"
  ],
  gemini: [
    pool_config: [size: 15, count: 3],
    base_url: "https://generativelanguage.googleapis.com"
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
